name: Backend Deploy to EC2
on:
  push:
    branches:
      - dev
    paths:
      - "backend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js dependencies
        working-directory: ./backend
        run: npm i
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/qmonorepo
            pm2 stop 2
            git restore backend/package-lock.json
            git pull
            cd ./backend
            npm run db:migrate
            npm install
            pm2 start 2
