name: Deploy to EC2
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js dependencies
        working-directory: ./backend
        run: npm i
      - name: Build React frontend
        working-directory: ./frontend
        run: npm i && npm run build
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/qmonorepo
            git pull origin dev
            # Deploy Node.js backend
            cd ./backend
            npm install
            pm2 restart 2
            # Deploy React frontend
            cd ../frontend
            npm install
            pm2 restart 1









