name: Frontend deploy
on:
  push:
    branches:
      - dev
    paths:
      - "frontend/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_BUILD_INSTANCE_IP }}
          username: ${{ secrets.EC2_BUILD_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/qmonorepo
            git reset --hard
            git pull
            cd ./frontend
            npm install
            npm run build
            scp \
              -i ~/server.pem \ 
              -r dist \
              ${{ secrets.EC2_SERVE_SSH_USERNAME }}@${{ secrets.EC2_SERVE_INSTANCE_IP }}:~/qmonorepo/frontend
      - name: Restart pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SERVE_INSTANCE_IP }}
          username: ${{ secrets.EC2_SERVE_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            pm2 restart --name FE
